- name: update
  hosts: all
  tasks:
    dnf:
      update_cache: yes

- name: upgrade
  hosts: all
  tasks:
    dnf:
      name: "*"
      state: latest

- name: Check if reboot is needed
  hosts: all
  tasks:
    shell: dnf needs-restarting -r ; echo $?
      args:
      warn: false
    register: reboot_required_command

- name: Extract return code from output
  hosts: all
  tasks:
    set_fact:
      reboot_required: "{{ reboot_required_command.stdout_lines | last }}"

- name: Reboot
  hosts: all
  tasks:
    reboot:
    when: reboot_required == "1"
